# ruff: noqa: E501,I001
"""add_user_id_to_reports_and_sos

Revision ID: 8439884a80a8
Revises: add_sos_requests
Create Date: 2025-11-26 15:24:09.178404

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '8439884a80a8'
down_revision = 'add_sos_requests'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklist_url_domain'), table_name='blacklist_url')
    op.add_column('reports', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.add_column('sos_requests', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.drop_index(op.f('ix_sos_requests_created'), table_name='sos_requests')
    op.drop_index(op.f('ix_sos_requests_status'), table_name='sos_requests')
    op.create_foreign_key(None, 'sos_requests', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('otp_code', sa.String(), nullable=True))
    op.drop_constraint(op.f('white_listurl_domain_key'), 'white_listurl', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('white_listurl_domain_key'), 'white_listurl', ['domain'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'otp_code')
    op.drop_constraint(None, 'sos_requests', type_='foreignkey')
    op.create_index(op.f('ix_sos_requests_status'), 'sos_requests', ['status'], unique=False)
    op.create_index(op.f('ix_sos_requests_created'), 'sos_requests', ['created'], unique=False)
    op.drop_column('sos_requests', 'user_id')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'user_id')
    op.create_index(op.f('ix_blacklist_url_domain'), 'blacklist_url', ['domain'], unique=False)
    # ### end Alembic commands ###
